### ISSUE TITLE
How do I increase the resolution of the generated image

### ISSUE THREAD

**Issue by zhanghongyong123456** [TomLarrow/VQGAN-CLIP-Automation#1]
https://colab.research.google.com/drive/1ZAus_gn2RhTZWzOWUpPERNC0Q8OhZRTZ
When I build based on this link, I have a problem of out of memory after modifying the large resolution. Where should I modify to increase the resolution
I'm not sure what I should change to improve the resolution，I hope you can give me some advice
Looking forward to your reply
![32](https://user-images.githubusercontent.com/48466610/123735053-13fc5300-d8d1-11eb-9086-3a7077b1d5f4.png)
![31](https://user-images.githubusercontent.com/48466610/123735063-178fda00-d8d1-11eb-82b5-cc50ba9a1b52.png)
![30](https://user-images.githubusercontent.com/48466610/123735069-1b236100-d8d1-11eb-9d3d-68ca78a58ed4.png)

**Comment by TomLarrow** [comment]
Increasing the resolution requires a lot more memory than Google Colab provides in its instances. In my own testing I still was unable to get a 720p image with 32GB memory on my own system. Likely you'd need 64GB or more to try and do some of the resolutions you are attempting
